### ISSUE TITLE
Extra window bar on top of maximized firefox window when its title bar is disabled (a.k.a using firefox's CSD)

### ISSUE THREAD

**Issue by kennethso168** [vinceliuice/matcha#37]
Distro: Manjaro
DE: Cinnamon
Matcha theme version: 20181007-1

Steps to reproduce:

1. Set the theme as follows in cinnamon settings:
![screenshot from 2018-10-10 22-23-09](https://user-images.githubusercontent.com/5262487/46743663-262aa300-ccdc-11e8-9f4d-2975187d90ee.png)

2. Go to Firefox > Customize > uncheck "Title Bar" at the bottom left corner

3. A extra bar is produced on top of the window when maximized:
![screenshot from 2018-10-10 22-22-34](https://user-images.githubusercontent.com/5262487/46743798-61c56d00-ccdc-11e8-939a-0c80d9bc43b4.png)

4. Neither a logout or a reboot solves the issue.

For comparison, this does not occur with other themes, including arc, which matcha is based on.
![screenshot from 2018-10-10 22-24-05](https://user-images.githubusercontent.com/5262487/46743854-815c9580-ccdc-11e8-8b47-1d76dabeb1e1.png)

And it does not occur with other programs using CSD, such as pamac and chromium
![screenshot from 2018-10-10 22-27-06](https://user-images.githubusercontent.com/5262487/46743901-9afddd00-ccdc-11e8-853c-2f958efb8b4d.png)

Thank you!

**Comment by Stebs** [comment]
Stumbled upon the same bug.
"Window borders" of some other Themes also have this "extra space on top" bug, although the size of the extra space is variable from Theme to Theme.
Workaround for now is setting "Window borders" to the Arc Theme.

**Comment by vinceliuice** [comment]
There are some issues on metacity theme, I'll fix it

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by themew** [comment]
Still seeing this occur in XFCE on Manjaro with matcha version 20181101

**Comment by Stebs** [comment]
> Still seeing this occur in XFCE on Manjaro with Matcha version 20181101-1
My Laptop with XFCE on Manjaro never showed this bug, still does not with update to Matcha version 20181101-1.
My Desktop with Cinnamon on Manjaro had the bug and this is now fixed with 20181101-1!
Thanks vinceliuice :)

With Firefox, make sure that there is no folder-symlink to another theme in your profile (Manjaro does that sometimes), nor that  widget.content.gtk-theme-override is set to some theme...

**Comment by themew** [comment]
Hi Vince, confirmed there no folder-symlink present in the theme profile, and the widget.contect.gtk-theme-override which was set to Arc-Maia is removed.   Also tried this on a fresh install of Manjaro and same result.  Forgot to mention, this is a GTK2 machine running Matcha-dark-azul.
