### ISSUE TITLE
Theme parsing error: <data>:1:28: Expected ')' in color definition

### ISSUE THREAD

**Issue by mabod** [vinceliuice/matcha#55]
I am gnome on Manjaro Testing with 
```

matcha-gtk-theme 20190219-1
matcha-icon-theme 20190110-1
```
And I am seeing errors like this with Matcha and firefox:

```
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:28: Expected ')' in color definition
Feb 25 07:18:28 rakete firefox[6298]: Theme parsing error: <data>:1:72: Expected ')' in color definition
```

**Comment by vinceliuice** [comment]
Fixed now

**Comment by mabod** [comment]
This issue is not fixed! I just updated the them with `update-matcha-online.sh`. And I keep getting firefox errors:

```
Feb 26 13:50:44 rakete firefox[4592]: Theme parsing error: <data>:1:34: Expected ')' in color definition
Feb 26 13:50:44 rakete firefox[4592]: Theme parsing error: <data>:1:77: Expected ')' in color definition
```

**Comment by vinceliuice** [comment]
![_2019-02-26_21-58-37](https://user-images.githubusercontent.com/7604295/53418465-da6e6100-3a12-11e9-8b2d-83d805502418.png)
This is what I get from terminal, Maybe this is a issue of firefox itself

**Comment by mabod** [comment]
I see the errors in the journal and the console every time I start firefox :
```
16# journalctl -b | grep firefox
Feb 27 06:49:11 rakete firefox[3509]: Theme parsing error: <data>:1:34: Expected ')' in color definition
Feb 27 06:49:11 rakete firefox[3509]: Theme parsing error: <data>:1:77: Expected ')' in color definition
```

```
25# firefox

(firefox:6972): Gtk-WARNING **: 07:09:09.753: Theme parsing error: <data>:1:34: Expected ')' in color definition

(firefox:6972): Gtk-WARNING **: 07:09:09.753: Theme parsing error: <data>:1:77: Expected ')' in color definition
```


The same is true for thunderbird by the way.

I used `update-matcha-online.sh` to get the latest css files on Manjaro testing. The other versions are:
```
firefox 65.0.1-1
thunderbird 60.5.2-0
gnome-shell 1:3.30.2-1
```

**Comment by mabod** [comment]
I just realized that I see these errors even when I use the Materia them. So it does not seem to be Matcha related. Any idea where this error can come from?

**Comment by vinceliuice** [comment]
I also have idea about this, Maybe you can reset all firefox settings and start again

**Comment by mabod** [comment]
It is a firefox bug. It has already been reported:

https://bugzilla.mozilla.org/show_bug.cgi?id=1516101

The report claims it was fixed 9. Jan. 2019. I guess I have to wait for the next firefox update.

Thanks for your help!

**Comment by vinceliuice** [comment]
You are welcome!
