### ISSUE TITLE
Dark variant feature request

### ISSUE THREAD

**Issue by mythio** [vinceliuice/matcha#63]
The dark variants seem to lack a few things.
Like the chrome active tab and the toolbar let say in vscode which remain light.
![Screenshot from 2019-04-23 05-41-35](https://user-images.githubusercontent.com/32430197/56542007-ea29a200-658a-11e9-8336-e6650e459d67.png)
![Screenshot from 2019-04-23 05-41-54](https://user-images.githubusercontent.com/32430197/56542008-ea29a200-658a-11e9-975d-c770382999cf.png)

I've made some changes and would like to create a pull request if you allow.
![Screenshot from 2019-04-23 05-42-09](https://user-images.githubusercontent.com/32430197/56541990-e269fd80-658a-11e9-97ac-2d62ed9546e2.png)
![Screenshot from 2019-04-23 05-42-20](https://user-images.githubusercontent.com/32430197/56541992-e269fd80-658a-11e9-8e8a-77544009276d.png)

**Comment by vinceliuice** [comment]
Before I fixed #58 It was dark theme on Chrome, but it has issues on Chrome 73: https://github.com/vinceliuice/matcha/issues/58  and  https://github.com/vinceliuice/Qogir-theme/issues/50
menu and Download status bar text can issues on chrome 73, so I have to force it use light theme

**Comment by mythio** [comment]
Oh yes. It has to be something with the chrome 73 build.

**Comment by mythio** [comment]
I think in the latest version of Chrome v74 this issue is fixed.

**Comment by vinceliuice** [comment]
Yes, only the menu issues are still, maybe it'll fixed next version, anyway I think I can undo all changes now.

**Comment by rmountjoy92** [comment]
I love this theme (thank you for all of your work on it), but for me the white menus for the dark variant in chrome/all electron app is a major flaw that I can't get over. Any chance this will be fixed in the near future? I would love to keep using this theme.
